default_context:
  _pegasus_version: '2023.12'
  author_name: Christian
  ci: github_actions
  css_framework: bootstrap
  css_theme: default
  database: postgres
  deploy_platform: digital_ocean_app_platform
  description: python tutorial
  docker_setup: arm64
  domain_name: localhost:8000
  email: codenestcompany@gmail.com
  enable_github_login: n
  enable_google_login: n
  enable_twitter_login: n
  front_end_framework: react
  include_static_files: y
  marketing_email_platform: email_octopus
  post_process: y
  project_name: PythonTutorial
  project_slug: dashboard
  stripe_payment_mode: checkout
  subscription_billing_model: default
  subscription_pricing_ui: in_app
  use_2fa: y
  use_admin_docs: y
  use_api_keys: n
  use_async_example: y
  use_cloud_media_storage: y
  use_debug_toolbar: y
  use_docker: y
  use_ecommerce_example: y
  use_examples: y
  use_impersonation: n
  use_openai: y
  use_sentry: y
  use_subscriptions: n
  use_teams: n
  use_teams_example: n
  use_translations: y
  use_wagtail: y